language: java
jdk:
  - openjdk11
sudo: true
dist: xenial

addons:
  apt:
    packages:
      - google-chrome-stable
env:
  - NODE_VERSION="12.14.0"
before_install:
  - nvm install $NODE_VERSION
install:
  - rm -rf node_modules
script: sh ./.travis.script.sh
