language: java
jdk:
  - oraclejdk8
dist: trusty

addons:
    chrome: stable
before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install: true
script: sh ./.travis.script.sh
