language: java
jdk:
  - oraclejdk8
sudo: true
dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
env:
  - NODE_VERSION="10.16.3"
before_install:
  - nvm install $NODE_VERSION
install: true
script: sh ./.travis.script.sh
